version: "3"

networks:
  corp:
    driver: bridge

services:
  api0:
    container_name: api0
    networks:
      - corp
    build: ./api
    ports:
      - "9001:9000"
  api1:
    container_name: api1
    networks:
      - corp
    build: ./api
    ports:
      - "9002:9000"
  api2:
    container_name: api2
    networks:
      - corp
    build: ./api
    ports:
      - "9003:9000"        
  web:
    container_name: web0
    networks:
      - corp
    build: .
    ports:
      - "80:80"